apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  selector:
    app: user-svc
  ports:
    - protocol: TCP
      port: 3000         # Port inside the cluster
      targetPort: 3000    # Port the app is listening on
      nodePort: 30010   # Exposed external port
  type: NodePort

