apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  selector:
    app: product-svc
  ports:
    - protocol: TCP
      port: 3000         # Port inside the cluster
      targetPort: 3000    # Port the app is listening on
      nodePort: 30040   # Exposed external port
  type: NodePort


