apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-svc
  template:
    metadata:
      labels:
        app: payment-svc
    spec:
      containers:
      - name: payment-svc
        image: shoaib2311/payment:latest
        ports:
        - containerPort: 8080
